# Generated by Django 3.0 on 2019-12-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='disscount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
