# Generated by Django 3.0 on 2019-12-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_disscount_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='disscount_price',
            new_name='discount_price',
        ),
    ]
