# Generated by Django 3.0 on 2019-12-29 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_order_being_delivered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',)},
        ),
    ]
