# Generated by Django 3.0 on 2019-12-29 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20191229_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-id',)},
        ),
    ]
